// poc-4/hotels/screens/hotelListingScreen/components/ratingStar.jsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
// import {   Star } from 'lucide-react-native';

const RatingStar = () => {
  const RatingBox = ({ rating }) => (
    <View style={styles.ratingBox}>
      <Text style={styles.ratingText}>{rating}<Ionicons name="star" size={20} color="#fdcc0d" /></Text>
    </View>
  );

  return (
    <View style={styles.container}>
      <Text style={styles.heading}>Rating Star</Text>
      <View style={styles.ratingContainer}>
        <RatingBox rating="3" />
        <RatingBox rating="3.5" />
        <RatingBox rating="4" />
        <RatingBox rating="4.5" />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#ddd',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 5,
    width: 300,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  heading: {
    marginTop: 0,
    fontWeight: 'bold',
    fontSize: 18,
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  ratingBox: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#ccc',
    // backgroundColor: '#ccc',
  },
  ratingText: {
    margin: 0,
    lineHeight: 20,
    fontSize: 16,
    color: 'black',
  },
});

export default RatingStar;

// poc-3/hotels/src/webpages/hotelListingPage/components/RatingStarComponent.vue
<template>
  <div>
    
    <div class="rating-container">
      <h2 class="rating-heading">Rating Star</h2>
      <div class="rating-boxes">
        <RatingBox rating="3" />
        <RatingBox rating="3.5" />
        <RatingBox rating="4" />
        <RatingBox rating="4.5" />
      </div>
    </div>
  </div>
</template>

<script>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faStar } from '@fortawesome/free-solid-svg-icons';

export default {
  name: 'RatingStar',
  components: {
    RatingBox: {
      props: {
        rating: String,
      },
      template: `
        <div class="rating-box">
          <p class="rating-value">{{ rating }}<font-awesome-icon icon="star" /></p>
        </div>
      `,
      components: {
        FontAwesomeIcon,
      },
    },
  },
};
</script>

<style scoped>
.rating-container {
  padding: 20px;
  border: 1px solid #ddd;
  border-radius: 2px;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
  width: 300px;
}

.rating-heading {
  margin-top: 0;
}

.rating-boxes {
  display: flex;
}

.rating-box {
  text-align: center;
  margin: 5px;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  box-sizing: border-box;
  background-color: #ccc;
}

.rating-value {
  margin: 0;
  line-height: 20px;
  font-size: 16px;
  color: black;
}
</style>
