// poc-3/hotels/src/webpages/hotelListingPage/components/PopularTypeComponent.vue
<template>
  <div>
    <div style="padding: 20px; border: 1px solid #ddd; border-radius: 5px; box-shadow: 0 0 2px rgba(0, 0, 0, 0.1);">
      <h2>Popular Type</h2>
      <div>
        <label>
          <input type="checkbox" v-model="freeBreakfastIncluded" />
          Free Breakfast Included
        </label>
      </div>
      <div>
        <label>
          <input type="checkbox" v-model="payAtHotelAvailable" />
          Pay At Hotel Available
        </label>
      </div>
      <div>
        <label>
          <input type="checkbox" v-model="freeCancellationAvailable" />
          Free Cancellation Available
        </label>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PopularType',
  data() {
    return {
      freeBreakfastIncluded: false,
      payAtHotelAvailable: false,
      freeCancellationAvailable: false,
    };
  },
};
</script>

<style scoped>
</style>

// poc-2/src/webPages/hotelListingPage/components/popular-type.jsx
import React from 'react'

export default function PopularType() {
  return (
    <div style={{ padding: '20px', border: '1px solid #ddd', borderRadius: '5px', boxShadow: '0 0 2px rgba(0, 0, 0, 0.1)',width:'300px' }}>
    <h2 style={{marginTop:0}}>Popular Type</h2>
    <div>
      <label>
        <input type="checkbox"/>
       Free Breakfast Included
      </label>
    </div>
    <div>
      <label>
        <input type="checkbox"/>
        Pay At Hotel Available
      </label>
    </div>
    <div>
      <label>
        <input type="checkbox"/>
        Free Cancellation Available
      </label>
    </div>
  </div>
  )
}
