// poc-3/hotels/src/webpages/hotelListingPage/components/HotelTypeComponent.vue
<template>
  <div style="padding: 20px; border: 1px solid #ddd; border-radius: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);">
    <h2 style="margin-top: 0;">Hotel Type</h2>
    
    <div>
      <label>
        <input
          type="checkbox"
          value="All"
          :checked="selectedTypes.includes('All')"
          @change="handleCheckboxChange('All')"
        />
        All
      </label>
    </div>

    <div v-for="type in ['Hotel', 'Apartment', 'Resort', 'Villa']" :key="type">
      <label>
        <input
          type="checkbox"
          :value="type"
          :checked="selectedTypes.includes(type)"
          @change="handleCheckboxChange(type)"
        />
        {{ type }}
      </label>
    </div>

    <!-- Additional content can be added here -->

  </div>
</template>

<script>
export default {
  name: 'HotelTypeFilter',
  data() {
    return {
      selectedTypes: [],
    };
  },
  methods: {
    handleCheckboxChange(type) {
      this.selectedTypes = this.selectedTypes.includes('All')
        ? type === 'All' ? [] : ['All', ...['Hotel', 'Apartment', 'Resort', 'Villa'].filter(t => t !== type)]
        : type === 'All' ? ['All', ...['Hotel', 'Apartment', 'Resort', 'Villa']] : (this.selectedTypes.includes(type)
          ? this.selectedTypes.filter(selectedType => selectedType !== type)
          : [...this.selectedTypes, type]);
    },
  },
};
</script>

<style scoped>
/* Add your styling here */
</style>

// hotels/src/webPages/hotelListingPage/components/hotel-type.jsx
import React, { useEffect } from 'react';
import { useFilter } from './fiterContext';

export default function HotelTypes({ data, onTypesChange }) {
  const { selectedTypes, setSelectedTypes } = useFilter();

  const handleCheckboxChange = (type) => {
    setSelectedTypes((prevSelectedTypes) => {
      if (type === 'All') {
        // If 'All' checkbox is clicked, toggle between selecting all and none
        return prevSelectedTypes.includes('All') ? [] :['All', ...data.items.map(hotel => hotel.type)] ;
      } else if (prevSelectedTypes.includes(type)) {
        // If the type is already selected, unselect it
        return prevSelectedTypes.filter((selectedType) => selectedType !== type);
      } else {
        // If the type is not selected, add it to the selection
        return [...prevSelectedTypes, type];
      }
      });
    };



  useEffect(() => {
    onTypesChange(selectedTypes);
  }, [selectedTypes, onTypesChange]);

  return (
    <div style={{ padding: '20px', border: '1px solid #ddd', borderRadius: '5px', boxShadow: '0 0 5px rgba(0, 0, 0, 0.1)', width: '300px' }}>
      <h2 style={{ marginTop: 0 }}>Hotel Type</h2>
      <div>
        <label>
          <input
            type="checkbox"
            value="All"
            checked={selectedTypes.includes("All")}
            onChange={() => handleCheckboxChange("All")}
          />
          All
        </label>
      </div>
      <div>
        <label>
          <input
            type="checkbox"
            value="Hotel"
            checked={selectedTypes.includes("Hotel")}
            onChange={() => handleCheckboxChange("Hotel")}
          />
          Hotel
        </label>
      </div>
      <div>
        <label>
          <input
            type="checkbox"
            value="Apartment"
            checked={selectedTypes.includes("Apartment")}
            onChange={() => handleCheckboxChange("Apartment")}
          />
          Apartment
        </label>
      </div>
      <div>
        <label>
          <input
            type="checkbox"
            value="Resort"
            checked={selectedTypes.includes("Resort")}
            onChange={() => handleCheckboxChange("Resort")}
          />
          Resort
        </label>
      </div>
      <div>
        <label>
          <input
            type="checkbox"
            value="Villa"
            checked={selectedTypes.includes("Villa")}
            onChange={() => handleCheckboxChange("Villa")}
          />
          Villa
        </label>
      </div>
      {/* <div style={{ display: 'flex', alignItems: 'center' }}>
        <span>See more</span>&nbsp;<FaAngleDown />
      </div> */}
    </div>
  );
}
