// poc-3/hotels/src/webpages/checkoutPage/components/checkinCheckout.component.vue
<template>
    <div class="checkinCheckoutContainer">
        <div class="cols">
          <label class="required dateLabels">Check-in Date</label>
          <input type="date" class="dateInputs" ref="checkinDate" v-on:input="handleCheckindate()" />
        </div>
        <div class="cols">
          <label class="required dateLabels">Check-out Date</label>
          <input type="date" class="dateInputs" ref="checkoutDate" v-on:input="handleCheckoutdate()" />
        </div>
    </div>
</template>
<script>
import { store } from '../../../store.js';

    export default{
        data(){
            return{
                store
            }
        },
        methods:{
            handleCheckindate(){
                var q = new Date();
                var date = new Date(q.getFullYear(),q.getMonth(),q.getDate());
                var userDate = new Date(this.$refs.checkinDate.value);

                if(date > userDate){
                    alert("checkin date cannot be in the past!");
                    this.$refs.checkinDate.value = "";
                }
                else{
                    store.checkinDate = userDate;
                    store.checkin = this.$refs.checkinDate.value;
                }
                
                // Sat Dec 30 2023 05:30:00 GMT+0530 (India Standard Time)
            },

            handleCheckoutdate(){
                var q = new Date();
                var userDate = new Date(this.$refs.checkoutDate.value);
                var presentDate = new Date(q.getFullYear(),q.getMonth(),q.getDate());

                if(userDate < presentDate || userDate < store.checkinDate){
                    alert("checkout date cannot be in the past compared to present and checkin date!");
                    this.$refs.checkoutDate.value = "";
                }
                else{
                    store.checkoutDate = userDate;
                    store.checkout = this.$refs.checkoutDate.value;
                }

            }
        }
    }
</script>
<style scoped src="../checkoutPage-styles/checkinCheckout.css"></style>

// hotels/src/webPages/checkoutPage/components/checkinCheckoutComponent.jsx
import { useState } from "react";
import style from "../checkout-page-styles/checkinCheckoutComponent.module.css";
import { TravellerComponent } from "./travellerDetailComponent";
import { SummaryComponent } from "./summaryComponent";

export let CheckInCheckOut = () => {
  let [state, setState] = useState({
    checkin: "",
    checkout: " ",
  });
  const updateDates = (e) => {
    const { name, value } = e.target;

    const currentDate = new Date();
    const selectedDate = new Date(value);
    // console.log(currentDate);
    // console.log(selectedDate);

    // Set the time portion to the end of the day
    selectedDate.setUTCHours(23, 59, 59, 999);

    if (name === "checkin" && selectedDate < currentDate) {
      alert("Check-in date cannot be in the past.");
      return;
    }

    if (name === "checkout" && selectedDate <= new Date(state.checkin)) {
      alert("Checkout date must be later than check-in date.");
      return;
    }
    setState((prevState) => ({ ...prevState, [name]: value }));
  };
  return (
    <>
      <div className={style.checkinCheckoutContainer}>
        <div className={style.cols}>
          <label className={`${style.required} ${style.dateLabels}`}>
            Check-in Date
          </label>
          <input
            type="date"
            name="checkin"
            value={state.checkin}
            className={style.dateInputs}
            onChange={updateDates}
          />
        </div>
        <div className={style.cols}>
          <label className={`${style.required} ${style.dateLabels}`}>
            Check-out Date
          </label>
          <input
            type="date"
            name="checkout"
            className={style.dateInputs}
            value={state.checkout}
            onChange={updateDates}
          />
        </div>
      </div>
      <TravellerComponent />
      <SummaryComponent checkin={state.checkin} checkout = {state.checkout} />
    </>
  );
};
