// poc-3/hotels/src/webpages/checkoutPage/components/summary.component.vue
<template>
    <div class="summaryContainer" v-on:click="display()">
      <div class="bookingDetails">
        <label for="checkInDate" class="bookingLabels">Check-In</label>
        <h4 class="summaryInp">{{ store.checkin }}</h4>
      </div>
      <div class="bookingDetails">
        <label for="checkOutDate" class="bookingLabels">Check-Out</label>
        <h4 class="summaryInp">{{ store.checkout }}</h4>
      </div>
      <div class="bookingDetails">
        <label for="amount" class="bookingLabels">Total Amount</label>
        <h4 class="summaryImp" style="color:green">${{ store.price*store.rooms }}</h4>
      </div>
    </div>
</template>
<script>
    import { store } from '../../../store.js';
    export default{
        data(){
            return{
                store
            }
        },
        methods:{
            
        }
    }
</script>
<style scoped src="../checkoutPage-styles/summary.css"></style>

// hotels/src/webPages/checkoutPage/components/summaryComponent.jsx
import { useSelector } from "react-redux";
import styles from "../checkout-page-styles/summaryComponent.module.css";

export let SummaryComponent = () => {

  const price = useSelector((state) => state.price);
  const checkin = useSelector((state) => state.checkin);
  const checkout = useSelector((state) => state.checkout);
  return (
    <div className={styles.summaryContainer}>
      <div className={styles.bookingDetails}>
        <label htmlFor="checkInDate" className={styles.bookingLabels}>
          Check-In
        </label>
        <input
          className={styles.summaryInp}
          id="checkIn"
          type="datetime"
          readOnly
          value={checkin}
        />
      </div>
      <div className={styles.bookingDetails}>
        <label htmlFor="checkOutDate" className={styles.bookingLabels}>
          Check-Out
        </label>
        <input
          className={styles.summaryInp}
          id="checkOutDate"
          type="datetime"
          readOnly
          value={checkout}
        />
      </div>
      <div className={styles.bookingDetails}>
        <label htmlFor="amount" className={styles.bookingLabels}>
          Total Amount
        </label>
        <input
          className={styles.summaryInp}
          style={{color:"green"}}
          type="text"
          id="amount"
          readOnly
          value={`$${price}`}
        />
      </div>
    </div>
  );
}
