// poc-3/hotels/src/webpages/checkoutPage/components/traveller.component.vue
<template>
    <div class="travellerContainer">
      <hr />
      <div class="travellerBanner">
        <h4></h4>
        <button class="removeTraveller" v-on:click="removeTraveller(this.data)">Remove</button>
      </div>
      <div class="travellerViewFor">
        <div class="colsFull">
          <label for="name" class="travellerLabel">Full name</label>
          <input class="travellerInput travellerInput1" type="text" />
          <input class="travellerInput travellerInput2" type="text" />
        </div>
        <div class="colsFull">
          <label for="dob" class="travellerLabel">Date of Birth</label>
          <input class="travellerInput travellerInput3" type="date"/>
        </div>
      </div>
    </div>
</template>
<script>
    import { store } from '../../../store.js';

    export default{
        props : ['data'],
        data(){
            return{
                store
            }
        },
        methods:{
            removeTraveller(val){
                console.log("value:", val);
                store.travellerDetailArr.splice(store.travellerDetailArr.indexOf(val), 1);
                store.travellerCount--;
                console.log("removed", store.travellerDetailArr);
                console.log("traveller count", store.travellerCount);
            }
        }
    }
</script>
<style scoped src="../checkoutPage-styles//traveller.css"></style>

// hotels/src/webPages/checkoutPage/components/traveller.jsx
import { useState } from "react";
import styles from "../checkout-page-styles/travellerDetailComponent.module.css";

export let Traveller = ({idn, onRemove}) => {
  let [user, setUser] = useState({
    firstname: "FirstName",
    lastname: "lastName",
  });
  console.log (idn)

  let addFirstName = (evt) => {
    setUser(() => ({ ...user, firstname: evt.target.value }));
  };
  let addLastName = (evt) => {
    setUser(() => ({ ...user, lastname: evt.target.value }));
  };

  let removeTraveller = () => {
    onRemove(idn)

  }
  return (
    <div className={styles.travellerContainer}>
      <hr />
      <div className={styles.travellerBanner}>
        <h4>
          {user.firstname} {user.lastname}
        </h4>
        <button className={styles.removeTraveller} onClick={removeTraveller}>
          Remove
        </button>
      </div>
      <div className={styles.travellerViewForm}>
        <div className={styles.colsFull}>
          <label htmlFor="name" className={styles.travellerLabel}> Full name</label>
          <input
            className={`${styles.travellerInput} ${styles.travellerInput1}`}
            type="text"
            onChange={addFirstName}
          />
          <input
            className={`${styles.travellerInput} ${styles.travellerInput2}`}
            type="text"
            onChange={addLastName}
          />
        </div>
        <div className={styles.colsFull}>
          <label htmlFor="dob" className={styles.travellerLabel}>Date of Birth</label>
          <input
            className={`${styles.travellerInput} ${styles.travellerInput3}`}
            type="date"
          />
        </div>
      </div>
    </div>
  );
};
