// poc-3/hotels/src/webpages/hotelListingPage/components/CustomerRatingComponent.vue
<template>
  <div>
    <div
      style="padding: 20px; border: 1px solid #ddd; border-radius: 5px; box-shadow: 0 0 2px rgba(0, 0, 0, 0.1);"
    >
      <h2 style="margin-top: 0">Customer Rating</h2>
      <div style="display: flex">
        <RatingBox
          v-for="rating in [3, 3.5, 4, 4.5]"
          :key="rating"
          :value="rating"
          @click="handleRatingClick(rating)"
          :is-selected="selectedRating === rating"
        />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'CustomerRating',
  data() {
    return {
      selectedRating: null,
    };
  },
  methods: {
    handleRatingClick(rating) {
      // Toggle the rating if clicked again
      const newRating = this.selectedRating === rating ? null : rating;

      // Update the state
      this.selectedRating = newRating;

      // Notify the parent component about the selected rating
      this.$emit('rating-change', newRating);
    },
  },
  components: {
    RatingBox: {
      props: {
        value: Number,
        isSelected: Boolean,
      },
      methods: {
        handleClick() {
          // Emit a custom event to notify the parent component about the click
          this.$emit('click', this.value);
        },
      },
      template: `
        <div
          @click="handleClick"
          :style="{
            textAlign: 'center',
            margin: '5px',
            padding: '15px',
            border: '1px solid #ccc',
            borderRadius: '5px',
            boxSizing: 'content-box',
            backgroundColor: isSelected ? '#ccc' : 'white',
            cursor: 'pointer',
          }"
        >
          <p style="margin: 0; line-height: 20px; font-size: 16px; color: black">{{ value }}</p>
        </div>
      `,
    },
  },
};
</script>

<style scoped>
/* Add your component-specific styles here */
</style>

// poc-4/hotels/screens/hotelListingScreen/components/customerRating.jsx
import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';

const CustomerRating = ({ onRatingChange }) => {
  const [selectedRating, setSelectedRating] = useState(null);

  const handleRatingClick = (rating) => {
    // Toggle the rating if clicked again
    const newRating = selectedRating === rating ? null : rating;

    // Update the state
    setSelectedRating(newRating);

    // Notify the parent component about the selected rating if onRatingChange is provided
    onRatingChange && onRatingChange(newRating);
  };

  return (
    <View style={styles.container}>
      <Text style={styles.heading}>Customer Rating</Text>
      <View style={styles.ratingContainer}>
        {[3, 3.5, 4, 4.5].map((rating) => (
          <RatingBox
            key={rating}
            value={rating}
            onClick={() => handleRatingClick(rating)}
            isSelected={selectedRating === rating}
          />
        ))}
      </View>
    </View>
  );
};

const RatingBox = ({ value, onClick, isSelected }) => (
  <TouchableOpacity onPress={onClick} style={[styles.ratingBox, isSelected && styles.selectedBox]}>
    <Text style={styles.ratingText}>{value}</Text>
  </TouchableOpacity>
);

const styles = StyleSheet.create({
  container: {
    padding: 20,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#ddd',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 5,
    width: 300,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  heading: {
    marginTop: 0,
    fontWeight: 'bold',
    fontSize: 18,
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  ratingBox: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#ccc',
    backgroundColor: 'white',
    cursor: 'pointer',
  },
  selectedBox: {
    backgroundColor: '#ccc',
  },
  ratingText: {
    margin: 0,
    lineHeight: 20,
    fontSize: 16,
    color: 'black',
  },
});

export default CustomerRating;
