// poc-3/hotels/src/webpages/hotelListingPage/components/PopularTypeComponent.vue
<template>
  <div>
    <div style="padding: 20px; border: 1px solid #ddd; border-radius: 5px; box-shadow: 0 0 2px rgba(0, 0, 0, 0.1); width: 300px;">
      <h1>Popular Type</h1>
      <div>
        <label>
          <input type="checkbox" v-model="freeBreakfastIncluded" />
          Free Breakfast Included
        </label>
      </div>
      <div>
        <label>
          <input type="checkbox" v-model="payAtHotelAvailable" />
          Pay At Hotel Available
        </label>
      </div>
      <div>
        <label>
          <input type="checkbox" v-model="freeCancellationAvailable" />
          Free Cancellation Available
        </label>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PopularType',
  data() {
    return {
      freeBreakfastIncluded: false,
      payAtHotelAvailable: false,
      freeCancellationAvailable: false,
    };
  },
};
</script>

<style scoped>
/* Add any additional styles if needed */
</style>

// poc-4/hotels/screens/hotelListingScreen/components/popularType.jsx
import React, { useState } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { CheckBox } from 'react-native-elements';

const PopularType = () => {
  const [checkedItems, setCheckedItems] = useState({
    'Free Breakfast Included': false,
    'Pay At Hotel Available': false,
    'Free Cancellation Available': false,
  });

  const handleCheckboxChange = (item) => {
    setCheckedItems((prevCheckedItems) => ({
      ...prevCheckedItems,
      [item]: !prevCheckedItems[item],
    }));
  };

  return (
    <View style={styles.container}>
      <Text style={styles.heading}>Popular Type</Text>
      <View style={styles.checkboxContainer}>
        <CheckBox
          title="Free Breakfast Included"
          checked={checkedItems['Free Breakfast Included']}
          onPress={() => handleCheckboxChange('Free Breakfast Included')}
        />
      </View>
      <View style={styles.checkboxContainer}>
        <CheckBox
          title="Pay At Hotel Available"
          checked={checkedItems['Pay At Hotel Available']}
          onPress={() => handleCheckboxChange('Pay At Hotel Available')}
        />
      </View>
      <View style={styles.checkboxContainer}>
        <CheckBox
          title="Free Cancellation Available"
          checked={checkedItems['Free Cancellation Available']}
          onPress={() => handleCheckboxChange('Free Cancellation Available')}
        />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#ddd',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 5,
    width: 300,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  heading: {
    marginTop: 0,
    fontWeight: 'bold',
    fontSize: 18,
  },
  checkboxContainer: {
    marginTop: 10,
  },
});

export default PopularType;
