// hotels/src/webPages/hotelDetailPage/components/section5.jsx
import "./section5.css"

export let DetailSectionFive = () => {
  return (
    <div className="hotel-policies-maincontainer">
    
      <div className="room-options-heading-div">
        <h1>Hotel Policies</h1>
        <hr/>
      </div>

      <div className="hotel-options-content">
        <p>
        <img src="assets/images/check.svg" alt=""/>
          &nbsp Drinking and smoking within controlled limits are permitted at the farmhouse but please do not create a
          mess
          or ruckus at the house.</p>
        <p>
        <img src="assets/images/check.svg" alt=""/>
          &nbsp Drugs and intoxicating illegal products are banned and not to be brought to the house or consumed.
        </p>
      </div>
    </div>
  );
};

// poc-3/hotels/src/webpages/hotelDetailPage/components/section-5.vue
<template>
  <div class="hotel-policies-maincontainer">
    <div class="room-options-heading-div">
      <h1>Hotel Policies</h1>
      <hr/>
    </div>

    <div class="hotel-options-content">
      <p>
        <font-awesome-icon :icon="['fas', 'circle-check']" style="color: green;"/>
        &nbsp; Drinking and smoking within controlled limits are permitted at the farmhouse but please do not create a mess or ruckus at the house.
      </p>
      <p>
        <font-awesome-icon :icon="['fas', 'circle-check']" style="color: green;"/>
        &nbsp; Drugs and intoxicating illegal products are banned and not to be brought to the house or consumed.
      </p>
    </div>
  </div>
</template>

<script>
export default {

};
</script>

<style src="../hotelDetails-styles/section-5.css" scoped></style>
