// poc-4/hotels/screens/homePage/components/section2.jsx
import { Image, ScrollView, Text, View } from "react-native";
import { styles } from "./section2";
import { ShieldCheck, Star, Timer, Utensils, Zap } from "lucide-react-native";

const image1 = require("../../../assets/images/01(1).jpg");

export default function Section2() {
  return (
    <ScrollView>
      <View>
        <Image source={image1} style={styles.adImage} />
      </View>
      {/* container containing rating display information */}
      <View style={styles.likesDisplay}>
        <View style={styles.ratingDisplayHeadings}>
          <Text style={styles.headding3}>Client</Text>
          <Text style={styles.headding3}>Rating</Text>
        </View>
        <View style={styles.ratingDisplayContent}>
          {/* container containing images of clients in rating display */}
          <View style={styles.clientImages}>
            <Image
              style={[styles.clientImageStyles, { top: 0, left: 0, zIndex: 1 }]}
              source={require("../../../assets/images/01.jpg")}
            />
            <Image
              style={[
                styles.clientImageStyles,
                { top: 0, left: 40, zIndex: 2 },
              ]}
              source={require("../../../assets/images/02.jpg")}
            />
            <Image
              style={[
                styles.clientImageStyles,
                { top: 0, left: 80, zIndex: 3 },
              ]}
              source={require("../../../assets/images/03.jpg")}
            />
            <Image
              style={[
                styles.clientImageStyles,
                { top: 0, left: 120, zIndex: 3 },
              ]}
              source={require("../../../assets/images/04.jpg")}
            />
          </View>
          <View>
            <Text style={styles.headding2}>
              4.5
              <Star fill="yellow" />
            </Text>
          </View>
        </View>
      </View>
      {/* container containing the content - like some of highlighted services  */}
      <View>
        <Text style={[{ fontWeight: "bold" }, styles.heading1]}>
          The Best Holidays Start Here
        </Text>
        <Text style={styles.parah}>
          Book your hotel with us and don't forget to grab an awesome hotel
          deals to save a massive on your stay.
        </Text>
        <View style={styles.commonServicesContainer}>
          <View style={styles.commonServices}>
            <View
              style={[
                { backgroundColor: "rgba(51, 225, 222, 0.2)" },
                styles.iconContainer,
              ]}
            >
              <Utensils color="rgb(51, 225, 222)" />
            </View>
            <Text style={styles.headding3}> Quality Food</Text>
          </View>
          <Text style={styles.parah}>
            Departure defective arranging rapturous did. Conduct denied adding
            worthy little.
          </Text>

          <View style={styles.commonServices}>
            <View
              style={[
                { backgroundColor: "rgba(223, 58, 82, 0.2)" },
                styles.iconContainer,
              ]}
            >
              <Timer color="rgb(223, 58, 82)" />
            </View>
            <Text style={styles.headding3}> Quick services</Text>
          </View>
          <Text style={styles.parah}>
            Supposing so be resolving breakfast am or perfectly.
          </Text>

          <View style={styles.commonServices}>
            <View
              style={[
                { backgroundColor: "rgba(226, 81, 3, 0.2)" },
                styles.iconContainer,
              ]}
            >
              <ShieldCheck color="rgb(226, 81, 3)" />
            </View>
            <Text style={styles.headding3}> High Security</Text>
          </View>
          <Text style={styles.parah}>
            Arranging rapturous did believe him all had supported.
          </Text>

          <View style={styles.commonServices}>
            <View
              style={[
                { backgroundColor: "rgba(48, 253, 185, 0.2)" },
                styles.iconContainer,
              ]}
            >
              <Zap fill="rgb(48, 253, 185)" />
            </View>
            <Text style={styles.headding3}> 24 Hours Alert</Text>
          </View>
          <Text style={styles.parah}>
            Rapturous did believe him all had supported.
          </Text>
        </View>
      </View>
    </ScrollView>
  );
}

// poc-3/hotels/src/webpages/homePage/components/section2.vue
<template>
    <section class="section2">
      <div class="section2-div left-image">
          <img class="adImage" src="/assets/images/01(1).jpg" alt="ADVERISEMENTS"/>
          <img class="star-top" src="/assets/images/starTop1.svg" alt="starImage"/>

          <div class="likes-display">
              <div class="outer-image">
                  <img src="/assets/images/01.svg" alt="like"/>
              </div>
              <div class="client-rating-display">
                  <div class="client-images">
                      <h3>Client</h3>
                      <div class="inner-images">
                          <img src="/assets/images/01.jpg" alt="image01"/>
                          <img src="/assets/images/02.jpg" alt="image02"/>
                          <img src="/assets/images/03.jpg" alt="image03"/>
                          <img src="/assets/images/04.jpg" alt="image04"/>
                      </div>
                  </div>
                  <div class="ratings">
                      <h3>Rating</h3>
                      <p>4.5 
                        <font-awesome-icon :icon="['fas', 'star']" style="color: #ffdf00"/>
                        </p>
                  </div>
              </div>
          </div>
      </div>
      <div class="section2-div right-content">
          <h1>The Best Holidays Start Here!</h1>
          <p>Book your hotel with us and don't forget to grab an awesome hotel deals to save a massive on your
              stay.
          </p>
          <div class="section_2 inner-grid-container">
              <div class="grid-content">

                  <i class="fa-solid fa-utensils">
                    <font-awesome-icon :icon="['fas', 'utensils']" class="utensils"/>
                  </i>
                  <h3>Quality Food</h3>
                  <p>
                      Departure defective arranging rapturous did. Conduct denied adding worthy little.
                  </p>
              </div>
              <div class="grid-content">

                      <i class="fa-solid fa-stopwatch">
                        <font-awesome-icon :icon="['fas', 'stopwatch']" class="stopwatch"/>
                      </i>
                      <h3>Quick Services</h3>
                  
                      <p>
                          Supposing so be resolving breakfast am or perfectly.
                      </p>
                 

              </div>
              <div class="grid-content">

                <i class="fa-solid fa-shield">
                    <font-awesome-icon :icon="['fas', 'shield']" class="shield"/>
                </i>
                
                <h3>High Security</h3>
                  <p>
                      Arranging rapturous did believe him all had supported.
                  </p>
              </div>
              <div class="grid-content">

                  <i class="fa-solid fa-bolt">
                    <font-awesome-icon :icon="['fas', 'bolt']" class="bolt"/>
                  </i>
                  <h3>24 Hours Alert</h3>
                  <p>
                      Rapturous did believe him all had supported.
                  </p>
              </div>
          </div>

      </div>
  </section>
</template>

<script>
    export default{
        data(){
            return{

            }
        }
    }
</script>

<style src="../homePage-styles/section2.css" scoped></style>
