// poc-4/hotels/screens/homePage/components/testimonial.jsx
import { Image, ScrollView, Text, View } from "react-native";
import { styles } from "../homePage-styles/testimonial";
import {  Star, StarHalf } from 'lucide-react-native';

export let Testimonial = (props) => {
    return(
        <>
                <View style={styles.section4_section}>

                    {/* section4 left division containing image */}
                    <View style={styles.section4_left_img_div}>
                        {/* <View style={styles.section4_left_sub_img_div}>
                            <Image source={require('../../../assets/images//03.svg')}/>
                        </View> */}
                        <Image source={props.testimonial.section4_left_img_1}  style={styles.section4_left_img}/>
                    </View>

                    {/* section4 right division containig text */}
                    <View style={styles.section4_right_text_div}>
                        <Image source={require('../../../assets/images/double-quote.png')} style={styles.doubleQuote}/>

                        <Text style={styles.section4_right_text_div_text}>Passage its ten led hearted removal cordial. Preference any astonished unreserved Mrs.Understood the preference unreserved.</Text>

                        <View style={styles.rating_div}>
                            <Star  fill="#fdcc0d" size="20"/>
                            <Star  fill="#fdcc0d" size="20"/>
                            <Star  fill="#fdcc0d" size="20"/>
                            <Star  fill="#fdcc0d" size="20"/>
                            <StarHalf   fill="#fdcc0d" size="20"/>
                        </View>

                        <Text style={styles.user_name}>{props.testimonial.section4_customer_name}</Text>

                        <Text style={styles.occupation_text}>occupation</Text>
                    </View>
                </View>
        </>
    )
}

// poc-3/hotels/src/webpages/homePage/components/testimonial.vue
<template>
  <div>
    <section :id="testimonial.section4_testimonial_id" class="section4_section">
      <!-- section4 left division containing image -->
      <div class="section4_left_img_div">
        <div class="section4_left_sub_img_div">
          <img :src="testimonial.section4_left_sub_img" alt="section4_left_sub_img" class="section4_left_sub_img" />
        </div>
        <img :src="testimonial.section4_left_img_1" alt="section4_left_img_1" class="section4_left_img" />
      </div>

      <!-- section4 right division containing text -->
      <div class="section4_right_text_div">
        <img src="/assets/images/double-quote.png" alt="double-quote" class="double-quote" />

        <p class="section4_right_text_div_p" id="section4_right_text_div_p3_1">
          Passage its ten led hearted removal cordial. preference any astonished unreserved Mrs.Understood the preference
          unreserved.
        </p>

        <!-- user ratings -->
        <font-awesome-icon class="rating_star" icon="fa-solid fa-star" />
        <font-awesome-icon class="rating_star" icon="fa-solid fa-star" />
        <font-awesome-icon class="rating_star" icon="fa-solid fa-star" />
        <font-awesome-icon class="rating_star" icon="fa-solid fa-star" />
        <font-awesome-icon class="rating_star" icon="fa-solid fa-star-half-stroke" />

        <!-- user name and occupation -->
        <b>
          <p class="section4_customer_name">{{ testimonial.section4_customer_name }}</p>
        </b>
        <p class="section4_customer_occupation">occupation</p>
      </div>
    </section>
  </div>
</template>

<script>


export default {
  props: {
    testimonial: Object,
  },
  components: {

  },
};
</script>

<style src="../homePage-styles/section4.css" scoped></style>
